# This is a Netlify configuration file.
# It tells Netlify how to build and deploy your site.

[build]
  # This tells Netlify where your serverless functions are located.
  functions = "netlify/functions/"

# This plugin automatically installs the necessary dependencies for your functions.
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
